<%@ Page Title=" Menu Category" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="categorymaster.aspx.cs" Inherits="categorymaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">


 <div class="row">
 <div class="col-md-12">
            <asp:Label ID="Label3" runat="server" Text="Menu Category" Font-Bold="true" Font-Size="XX-Large"></asp:Label><br />
            <br />
            <asp:Label ID="lbl" runat="server" Text=""></asp:Label><br />
            <br />
            <asp:Label ID="Lblname" runat="server" Text="Name" Font-Bold="true"> </asp:Label>
            <asp:TextBox ID="txtname" runat="server"></asp:TextBox><br />
            <br />
            <asp:Label ID="Lblcomment" runat="server" Text="Comment" Font-Bold="true"></asp:Label>
            <asp:TextBox ID="txtcomment" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" Text="Submit" OnClick="Button1_Click" />
            <asp:Button ID="Button2" runat="server" Text="Clear" OnClick="Button2_Click" /><br />
            <br />
            </div>
</div>


 <div class="row">
 <div class="col-md-12">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CssClass="table table-striped table-hover table-responsive"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" 
        DataKeyNames="categorynumber" DataSourceID="SqlDataSource1" 
        GridLines="None">
        
        <Columns>
            <asp:BoundField DataField="categorynumber" HeaderText="categorynumber" 
                InsertVisible="False" ReadOnly="True" SortExpression="categorynumber" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Comment" HeaderText="Comment" 
                SortExpression="Comment" />
                <asp:TemplateField HeaderText="View Item">
                <ItemTemplate>
                <a target="list" href="itemsincategory.aspx?categoryno=<%# Eval("categorynumber") %>">Item List</a>
                </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="View Item">
                <ItemTemplate>
                <a target="edit" href="edititemsincategory.aspx?categoryno=<%# Eval("categorynumber") %>">Edit List</a>
                </ItemTemplate>
                </asp:TemplateField>
        </Columns>
        <HeaderStyle BackColor="Yellow" Font-Bold="True" ForeColor="White" />
    </asp:GridView>



 
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ResturantConnectionString %>" 
        DeleteCommand="delete from menucategory where categorynumber=@categorynumber"
        UpdateCommand="UPDATE [dbo].[menucategory] SET [Name] = @Name, [Comment] = @Comment WHERE [categorynumber] = @categorynumber"
        SelectCommand="SELECT * FROM [menucategory] ORDER BY [Name]">
    </asp:SqlDataSource>

    </div>
    </div>

 
</asp:Content>

