<%@ Page Title="Category Master" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="categorymaster.aspx.cs" Inherits="categorymaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">

 <div>
            <asp:Label ID="Label3" runat="server" Text="Menu Category" Font-Bold="true" Font-Size="XX-Large"></asp:Label><br />
            <br />
            <asp:Label ID="lbl" runat="server" Text=""></asp:Label><br />
            <br />
            <asp:Label ID="Lblname" runat="server" Text="Name" Font-Bold="true"> </asp:Label>
            <asp:TextBox ID="txtname" runat="server"></asp:TextBox><br />
            <br />
            <asp:Label ID="Lblcomment" runat="server" Text="Comment" Font-Bold="true"></asp:Label>
            <asp:TextBox ID="txtcomment" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" Text="Submit" OnClick="Button1_Click" />
            <asp:Button ID="Button2" runat="server" Text="Clear" OnClick="Button2_Click" /><br />
            <br />


 <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4"
                DataKeyNames="categorynumber" DataSourceID="SqlDataSource1" ForeColor="#333333"
                GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <AlternatingRowStyle BackColor="White" />
                <Columns>

                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Comment" HeaderText="Comment" SortExpression="Comment" />
                    <asp:TemplateField HeaderText="View Item">
                        <ItemTemplate>
                            <a target="items" href='itemsincategory.aspx?categoryno=<%# Eval("categorynumber") %>'>
                                Item List</a>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="View Item">
                        <ItemTemplate>
                            <a target="itemsmaster" href='edititemsincategory.aspx?categorynumber=<%# Eval("categorynumber") %>'>
                                Edit Item</a>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                <SortedDescendingHeaderStyle BackColor="#820000" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ResturantConnectionString %>"
                DeleteCommand="delete from menucategory where categorynumber= @categorynumber"
                UpdateCommand="UPDATE [dbo].[menucategory] SET [Name] = @Name, [Comment] = @Comment WHERE [categorynumber] = @categorynumber"
                SelectCommand="SELECT * FROM [menucategory] ORDER BY [Name]"></asp:SqlDataSource>
</asp:Content>

