<%@ Page Title="edititem" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="edititemsincategory.aspx.cs" Inherits="edititemsincategory" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">

<div class="row">
<div class="col-md-12" >
   <asp:Label ID="Lbl" runat="server" Text="Edit Item List" Font-Bold="true" Font-Size="XX-Large"></asp:Label>

 <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CssClass="table table-hover table-responsive table-striped" 
        DataKeyNames="itemnumber" DataSourceID="SqlDataSource1" CellPadding="5" 
        ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" 
        style="margin-right: 17px" AutoGenerateEditButton="True">
        <AlternatingRowStyle BackColor="White" />
        
        <Columns>
            
                    <asp:BoundField DataField="itemname" HeaderText="itemname" 
                        SortExpression="itemname" />
                    <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
                    <asp:BoundField DataField="packing" HeaderText="packing" 
                        SortExpression="packing" />
        </Columns>
        
        <HeaderStyle BackColor="LightGreen" Font-Bold="True" ForeColor="White" />
        
 </asp:GridView>

<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                
                ConnectionString="<%$ ConnectionStrings:ResturantConnectionString %>" 
                DeleteCommand="delete from itemmenu where itemnumber = @itemnumber"
                UpdateCommand="UPDATE [dbo].[itemmenu] SET  [itemname] = @itemname,
                          [price] = @price, [packing] = @packing WHERE [itemnumber] = @itemnumber"
                SelectCommand="SELECT * FROM [itemmenu] WHERE ([categorynumber] = @categorynumber2) ORDER BY [itemname], [price]">
       
    <SelectParameters>
        <asp:QueryStringParameter Name="categorynumber2" QueryStringField="categoryno" 
            Type="Int32" />
    </SelectParameters>       
    
</asp:SqlDataSource>
</div>
</div>  

<div class="row">
<div class="col-md-12">
      <asp:Label ID="Label6" runat="server" Text=" To New Item Add" Font-Bold="true" Font-Size="XX-Large"></asp:Label><br /><br />
       <asp:Label ID="LblName" runat="server" Text="" Font-Bold="true" Font-size="X-Large"></asp:Label>
       <br /><br />
        <asp:Label ID="Labl" runat="server" Text="" Font-size="Larger"></asp:Label><br /><br />
    
        <asp:Label ID="Label3" runat="server" Text="Item Name" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtname" runat="server"></asp:TextBox><br /><br />

        <asp:Label ID="Label4" runat="server" Text="Price" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtprice" runat="server"></asp:TextBox><br /><br />

        <asp:Label ID="Label5" runat="server" Text="Packing" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtpacking" runat="server"></asp:TextBox><br /><br />


        <asp:Button ID="Button1" runat="server" Text="Submit" OnClick="Button1_Click" />
        <asp:Button ID="Button2" runat="server" Text="Clear" OnClick="Button2_Click" /><br /><br />


 </div>
 </div>  
    

</asp:Content>

