<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Item Menu.aspx.cs" Inherits="Item_Menu" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
<center>
    <form id="form1" runat="server">
    <div>
     <asp:Label ID="Label6" runat="server" Text="Item Menu" Font-Bold="true" Font-Size="XX-Large"></asp:Label><br /><br />
        <asp:Label ID="lbl" runat="server" Text=""></asp:Label><br /><br />

        <asp:Label ID="Label1" runat="server" Text="Category Number" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtcategoryno" runat="server"></asp:TextBox><br /><br />

        
        <asp:Label ID="Label3" runat="server" Text="Item Name" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtname" runat="server"></asp:TextBox><br /><br />

        <asp:Label ID="Label4" runat="server" Text="Price" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtprice" runat="server"></asp:TextBox><br /><br />

        <asp:Label ID="Label5" runat="server" Text="Packing" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtpacking" runat="server"></asp:TextBox><br /><br />


        <asp:Button ID="Button1" runat="server" Text="Submit" OnClick="Button1_Click" />
        <asp:Button ID="Button2" runat="server" Text="Clear" OnClick="Button2_Click" /><br /><br />



           <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
            BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" 
            CellPadding="2" DataKeyNames="itemnumber" DataSourceID="SqlDataSource1" 
            ForeColor="Black" GridLines="None" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            <Columns>
                
                <asp:BoundField DataField="categorynumber" HeaderText="categorynumber" 
                    SortExpression="categorynumber" />
                <asp:BoundField DataField="itemname" HeaderText="itemname" 
                    SortExpression="itemname" />
                <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
                <asp:BoundField DataField="packing" HeaderText="packing" 
                    SortExpression="packing" />
                
            </Columns>
            <FooterStyle BackColor="Tan" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" 
                HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <SortedAscendingCellStyle BackColor="#FAFAE7" />
            <SortedAscendingHeaderStyle BackColor="#DAC09E" />
            <SortedDescendingCellStyle BackColor="#E1DB9C" />
            <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ResturantConnectionString %>" 
            DeleteCommand="delete from itemmenu where itemnumber = @itemnumber"
             UpdateCommand="UPDATE [dbo].[itemmenu] SET [categorynumber] = @categorynumber, [itemname] = @itemname,
              [price] = @price, [packing] = @packing WHERE [itemnumber] = @itemnumber"
            SelectCommand="SELECT * FROM [itemmenu] ORDER BY [itemname]">
        </asp:SqlDataSource>




        




    </div>
    </form>
    </center>
</body>
</html>
