<%@ Page Title="ItemMenu" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="ItemMenumaster.aspx.cs" Inherits="ItemMenumaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">

<div class="row">
<div class="col-12">

<asp:Label ID="Label6" runat="server" Text="Item Menu" Font-Bold="true" Font-Size="XX-Large"></asp:Label><br /><br />
        <asp:Label ID="lbl" runat="server" Text=""></asp:Label><br /><br />

        <asp:Label ID="Label1" runat="server" Text="Category Number" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtcategoryno" runat="server"></asp:TextBox><br /><br />

        
        <asp:Label ID="Label3" runat="server" Text="Item Name" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtname" runat="server"></asp:TextBox><br /><br />

        <asp:Label ID="Label4" runat="server" Text="Price" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtprice" runat="server"></asp:TextBox><br /><br />

        <asp:Label ID="Label5" runat="server" Text="Packing" Font-Bold="true"></asp:Label>  
        <asp:TextBox ID="txtpacking" runat="server"></asp:TextBox><br /><br />


        <asp:Button ID="Button1" runat="server" Text="Submit" OnClick="Button1_Click" />
        <asp:Button ID="Button2" runat="server" Text="Clear" OnClick="Button2_Click" /><br /><br />




</div>
</div>

<div class="row">
<div class="col-12">

  <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CssClass="table table-striped table-hover table-responsive"
            BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" 
            CellPadding="7" DataKeyNames="itemnumber" DataSourceID="SqlDataSource1" 
            ForeColor="Black" GridLines="None" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            <Columns>
                
                <asp:BoundField DataField="categorynumber" HeaderText="categorynumber" 
                    SortExpression="categorynumber" />
                <asp:BoundField DataField="itemname" HeaderText="itemname" 
                    SortExpression="itemname" />
                <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
                <asp:BoundField DataField="packing" HeaderText="packing" 
                    SortExpression="packing" />
                
            </Columns>
           
            <HeaderStyle BackColor="Orange" Font-Bold="True" />
            
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ResturantConnectionString %>" 
            DeleteCommand="delete from itemmenu where itemnumber = @itemnumber"
             UpdateCommand="UPDATE [dbo].[itemmenu] SET [categorynumber] = @categorynumber, [itemname] = @itemname,
              [price] = @price, [packing] = @packing WHERE [itemnumber] = @itemnumber"
            SelectCommand="SELECT * FROM [itemmenu] ORDER BY [itemname]">
        </asp:SqlDataSource>




</div>
</div>

</asp:Content>

