<%@ Page Title="Tabledetails" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Tablemaster.aspx.cs" Inherits="Tablemaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <div class="row">
   <div class="col-12">
            <asp:Label ID="Label1" runat="server" Text="Table status" Font-Bold="true" Font-Size="X-Large"></asp:Label><br /><br />
            <asp:Label ID="lbl" runat="server" Text="" Font-Bold="true"></asp:Label><br /><br />

            

            <asp:Label ID="Label3" runat="server" Text="Table Name" Font-Bold="true"></asp:Label>  
            <asp:TextBox ID="txttablename" runat="server"></asp:TextBox><br /><br />


            <asp:Label ID="Label5" runat="server" Text="Comment" Font-Bold="true"></asp:Label> 
            <asp:TextBox ID="txtcomment" runat="server"></asp:TextBox><br /><br />

            <asp:Label ID="Label6" runat="server" Text="No of Seat" Font-Bold="true"></asp:Label> 
            <asp:TextBox ID="txtseat" runat="server"></asp:TextBox><br /><br />

           
       <asp:Button ID="Button1" runat="server" Text="Submit" OnClick="Button1_Click" />
        <asp:Button ID="Button2" runat="server" Text="Clear" OnClick="Button2_Click" /><br /><br />

            
     </div>
     </div>

   <div class="row">
   <div class="col-12">
       <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CssClass="table table-striped table-hover table-responsive"
           AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="7" 
           DataKeyNames="tableno" DataSourceID="SqlDataSource1" ForeColor="#333333" 
           GridLines="None">
           <AlternatingRowStyle BackColor="White" />
           <Columns>
               <asp:BoundField DataField="tableno" HeaderText="tableno" InsertVisible="False" 
                   ReadOnly="True" SortExpression="tableno" />
               <asp:BoundField DataField="tablename" HeaderText="tablename" 
                   SortExpression="tablename" />
               <asp:BoundField DataField="seatno" HeaderText="seatno" 
                   SortExpression="seatno" />
               <asp:BoundField DataField="status" HeaderText="status" 
                   SortExpression="status" />
               <asp:BoundField DataField="comment" HeaderText="comment" 
                   SortExpression="comment" />
                  <asp:TemplateField HeaderText="Booking Status">
                  <ItemTemplate>
                  <a target="" href="#">View Status</a>
                  </ItemTemplate>
                  </asp:TemplateField>
           </Columns>
           
           
           <HeaderStyle BackColor="Yellow" Font-Bold="True" ForeColor="White" />
           
       </asp:GridView>
       
       <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
           ConnectionString="<%$ ConnectionStrings:ResturantConnectionString %>"
           DeleteCommand="delete from tabledata where tableno = @tableno"
           UpdateCommand="UPDATE [dbo].[tabledata] SET [tablename] = @tablename, [seatno] = @seatno, [status] = @status, 
           [comment] = @comment WHERE [tableno] = @tableno"
           SelectCommand="SELECT * FROM [tabledata] ORDER BY [tablename], [seatno], [status]">
       </asp:SqlDataSource>
       
    </div>
    </div>

</asp:Content>

      
          


